### ISSUE TITLE
"Couldn't find/load text fonts" with Macplay files

### ISSUE THREAD

**Issue by triscuitcircuit** [alexbatalov/fallout2-ce#134]
When moving the files from the Macplay disc into a folder named "Fallout2" located with the applications folder, fallout-ce has an alert that says "Couldn't find/load text fonts" when ran

**Comment by alexbatalov** [comment]
I guess the problem is with `GameData` folder, which you copied inside your new `/Applications/Fallout2`. So effectively you now have this:
![fallout2-macplay-1](https://user-images.githubusercontent.com/172978/185295370-6418a1aa-6e0d-4130-af5f-f55f2ad24f87.png)

Copy files from `GameData` to the parent folder:
![fallout2-macplay-2](https://user-images.githubusercontent.com/172978/185295781-9d036ed3-840d-4c59-96c4-f93f89b3d4bf.png)

Don't forget to add `f2_res.ini` to the same folder so you can play in windowed mode with suitable resolution.
```ini
[MAIN]
SCR_WIDTH=1280
SCR_HEIGHT=720
WINDOWED=1

[IFACE]
IFACE_BAR_MODE=1
```

**Comment by triscuitcircuit** [comment]
Thanks, that works!
