### ISSUE TITLE
Android and ios ports ?

### ISSUE THREAD

**Issue by M1sh2** [alexbatalov/fallout2-ce#74]
Today can play fallout 2 only through emulators on phones.
Is it possible to compile for these systems ?

**Comment by alexeevdv** [comment]
Vanilla engine can be launched on Android [using emulator](https://4pda.to/forum/index.php?showtopic=302581). Same approach could be used for f2-ce. But it is not very convenient to play with emulator. As @alexbatalov mentioned it will take too much efforts to adapt UI and controls for mobile platforms. I don't think it is even possible yet because of huge amount of  code that is need to be refactored. Such changes would take much more than switching to SDL

**Comment by strikersix23** [comment]
any idea on gamedata location?

**Comment by strikersix23** [comment]
or am i supposed to bundle data build on android

**Comment by strikersix23** [comment]
for the ui you could take hints at 

https://github.com/xyzz/openmw-android

https://github.com/pelya/openttd-android
https://github.com/emileb/MobileTouchControls

https://github.com/emileb/

**Comment by alexbatalov** [comment]
Android port is available at https://github.com/alexbatalov/fallout2-ce/actions/runs/2762124461

**Comment by M1sh2** [comment]
https://4pda.to/forum/index.php?showtopic=1052741&st=0
On the Russian forum 4pda someone has created a theme, there have already offered a temporary solution to the implementation of control, as well as you can view comments on the problems.
